<?php
define("PROJECT_NAME", "Flexitol");

/**
 * Implements hook_block_info.
 */
function conf_block_block_info() {
  $blocks = array();

  $blocks['welcome_block'] = array(
    'info' => t('Welcome block'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view.
 */
function conf_block_block_view($delta = '') {
  $block = array();

  switch ($delta) {

    case 'welcome_block':
      $content = _conf_block_welcome_block_view();
      $block['content'] = $content;
      $block['subject'] = '';
      break;
  }

  return $block;
}

function _conf_block_welcome_block_view() {
  $block_data = variable_get('conf_block_welcome_block_data', array());
  $markup = "";


  //echo "<pre>";var_dump($block_data);echo "</pre>";


  $file = file_load($block_data['image']);
  $image = image_load($file->uri);
  $content = array(
    'file' => array(
      '#theme' => 'image_style',
      '#style_name' => 'large',
      '#path' => $image->source,
      '#width' => $image->info['width'],
      '#height' => $image->info['height'],
    ),
  );


  $img_markup = drupal_render($content);

  $markup .= "


    <div class='welcome-block'>
      <div class='row'>
        <div class='col-md-7'>
          <div class='text'>
            <h2>" . $block_data['title'] . "</h2>
            <p>" . $block_data['body'] . "</p>
          </div>
        </div>
        <div class='col-md-5 hidden-xs  hidden-sm'>
          <div class='image'>
            ".$img_markup."
          </div>
        </div>
      </div>
    </div>

  ";
  //$markup .= "<a class='btn btn-default' href=\"". $block_data['link'] . "\">Read more</a>";

  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => $markup,
      '#suffix' => '',
    ),
  );

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function conf_block_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'welcome_block' :
      $block_data = variable_get('conf_block_welcome_block_data', array());

      $form['conf_block_welcome_block_title'] = array(
        '#type' => 'textfield',
        '#title' => 'Main title',
        '#default_value' => isset($block_data['title']) ? $block_data['title'] : '',
      );

      $form['conf_block_welcome_block_body'] = array(
        '#type' => 'textarea',
        '#title' => 'Block Body',
        '#default_value' => isset($block_data['body']) ? $block_data['body'] : '',
      );

      $form['conf_block_welcome_block_image'] = array(
        '#title' => t('Image'),
        '#type' => 'managed_file',
        '#description' => t('The uploaded image will be displayed on this page using the image style choosen below.'),
        '#default_value' => isset($block_data['image']) ? $block_data['image'] : '',
        '#upload_location' => 'public://',
      );

      $form['conf_block_welcome_block_link'] = array(
        '#type' => 'textfield',
        '#title' => 'Read More Link Url',
        '#default_value' => isset($block_data['link']) ? $block_data['link'] : '',
      );

      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function conf_block_block_save($delta = '', $edit = array()) {

  switch ($delta) {
    case 'welcome_block' :
      $block_data =  array();

      if (isset($edit['conf_block_welcome_block_body'])) {
        $block_data['body'] = $edit['conf_block_welcome_block_body'];
      }

      if (isset($edit['conf_block_welcome_block_title'])) {
        $block_data['title'] = $edit['conf_block_welcome_block_title'];
      }

      if (isset($edit['conf_block_welcome_block_image'])) {
        $block_data['image'] = $edit['conf_block_welcome_block_image'];
      }
      if (isset($edit['conf_block_welcome_block_link'])) {
        $block_data['link'] = $edit['conf_block_welcome_block_link'];
      }
      variable_set('conf_block_welcome_block_data', $block_data);
      break;
  }
}
