<?php

/**
 * Implements hook_field_formatter_info().
 */
function dermal_generic_field_formatter_info() {
  $info = array(
    'bhfivestar' => array(
      'label' => t('BH Fivestar'),
      'field types' => array('text_long'),
      'description' => t('Show as the BH Review block'),
    ),
  );

  return $info;
}

/**
 * Implements hook_field_formatter_view().
 */
function dermal_generic_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'bhfivestar':
      $text_long = reset($items);
      if (!empty($text_long['value'])) {
        $bh_logo = drupal_get_path('module', 'dermal_generic') . '/img/beauty_review_logo.png';
        if (!empty($entity->field_beauty_review_link[LANGUAGE_NONE][0]['url'])) {
          $url = $entity->field_beauty_review_link[LANGUAGE_NONE][0]['url'];
          $markup = "
            <div class='bhrating'>
              <a href='{$url}' target='_blank'>
                <div class='left'><img src='/{$bh_logo}'/></div>
                <div class='right'>{$text_long['value']}</div>
              </a>
            </div>";
        }
        else {
          $markup = "
            <div class='bhrating'>
              <div class='left'><img src='/{$bh_logo}'/></div>
              <div class='right'>{$text_long['value']}</div>
            </div>";
        }
        $element[0] = array(
          '#markup' => $markup,
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_cron()
 *
 * @throws \Exception
 */
function dermal_generic_cron() {
  watchdog(WATCHDOG_ALERT, 'SYNC Beatury Heaven Reviews');

  $nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->fields('n', array('type'))
    ->condition('n.type', 'product')
    ->execute()
    ->fetchCol();
  $nodes = node_load_multiple($nids);
  $count = 0;
  foreach ($nodes as $node) {
    if (isset($node->field_beauty_review_link[LANGUAGE_NONE])) {
      $curl = curl_init($node->field_beauty_review_link[LANGUAGE_NONE][0]['url']);
      curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);
      curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10');
      $html = curl_exec($curl);
      curl_close($curl);

      $dom = new DOMDocument();
      @$dom->loadHTML($html);
      $xpath = new DOMXPath($dom);
      $rating = $xpath->query( "//div[contains(@class,'product-average-rating')]" );
      if ($rating->length === 1) {
        $count++;
        $rating_block = $dom->saveHTML($rating->item(0));
        $node->field_beauty_review_data[LANGUAGE_NONE][0]['value'] = $rating_block;
        $node->field_beauty_review_data[LANGUAGE_NONE][0]['#format'] = 'php_code';
        node_save($node);
      }
    }
  }

  watchdog(WATCHDOG_ALERT, "Added/updated {$count} reviews");
}

/**
 * Implements hook_node_presave().
 *
 * @param $node
 */
function dermal_generic_node_presave($node) {
    global $user;
    if ($node->type == 'product' && isset($node->nid) && isset($user->uid)) {
        $node->field_beauty_review_data = $node->original->field_beauty_review_data;
    }
}

/**
 * Implements hook_ds_pre_render_alter()
 *
 * @param $layout_render_array
 * @param $context
 * @param $vars
 */
function dermal_generic_ds_pre_render_alter(&$layout_render_array, $context, &$vars) {
  if ($context['entity_type'] == 'node' && $context['entity']->type == 'product') {
    $current = domain_get_domain();
    if ($current['machine_name'] == 'australia_dt') {
      $image = image_style_url('width_250', $context['entity']->field_product_image['und'][0]['uri']);
      $data = array(
        '#type' => 'markup',
        '#markup' => "<script type='application/ld+json'>
{
  '@context': 'https://schema.org/',
  '@type': 'Product',
  'name': '{$context['entity']->title}',
  'image': [
    '{$image}',
   ],
  'description': '{$context['entity']->field_product_information['und'][0]['value']}',
  'mpn': '925872',
  'brand': {
    '@type': 'Thing',
    'name': 'Dermal Therapy'
  }
  }
}
</script>");

      $layout_render_array['left'][] = $data;
    }
  }
}
